# Generated by Django 5.1.2 on 2024-10-28 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 18, 31, 56, 869130, tzinfo=datetime.timezone.utc)),
        ),
    ]
