# Generated by Django 5.1.2 on 2024-10-30 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_limit_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 9, 52, 50, 844266, tzinfo=datetime.timezone.utc)),
        ),
    ]
